package com.yma.course.model;
// Generated Aug 14, 2017 6:34:08 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Topic generated by hbm2java
 */
@Entity
@Table(name = "topic", catalog = "course_database")
public class Topic implements java.io.Serializable {

	private Integer topicId;
	@JsonIgnoreProperties("topics")
	private Course course;
	private String topicName;
	private String topicDescription;

	public Topic() {
	}

	public Topic(Course course, String topicName, String topicDescription) {
		this.course = course;
		this.topicName = topicName;
		this.topicDescription = topicDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "topic_id", unique = true, nullable = false)
	public Integer getTopicId() {
		return this.topicId;
	}

	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id")
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "topic_name", length = 100)
	public String getTopicName() {
		return this.topicName;
	}

	public void setTopicName(String topicName) {
		this.topicName = topicName;
	}

	@Column(name = "topic_description", length = 100)
	public String getTopicDescription() {
		return this.topicDescription;
	}

	public void setTopicDescription(String topicDescription) {
		this.topicDescription = topicDescription;
	}

}
